// ============================================
// 1 SKYRIUS - ĮVADAS
// ============================================

#import "../template.typ"

#heading(level: 1, numbering: none)[ĮVADAS]

*Temos aktualumas.* Skaitmeninė transformacija fundamentaliai keičia šiuolaikinės visuomenės funkcionavimo principus, o švietimo sritis šiame procese užima ypatingą vietą. Interaktyvumas -- daugiapusė sąveika tarp besimokančiojo, turinio ir technologijų -- tapo vienu esminių šiuolaikinio ugdymo kokybės rodiklių, tačiau kelias nuo pirmųjų kompiuterių mokyklose iki visiškai skaitmenizuoto ugdymo vizijos buvo ir tebėra kupinas iššūkių, nelygybės bei fundamentalių pedagoginių klausimų. Interaktyvumo švietime aktualumą itin pabrėžė COVID-19 pandemija, kuri 2020 metais privertė švietimo sistemas visame pasaulyje skubiai pereiti prie nuotolinio mokymo. Europos Komisijos atliktos apklausos atskleidė, kad iki pandemijos tik apie 40 proc. Europos Sąjungos mokytojų jautėsi pasirengę naudoti skaitmenines technologijas ugdymo procese (OECD, 2019). Ši krizė ne tik išryškino egzistuojančias skaitmenines spragas, bet ir paskatino precedento neturinčią švietimo technologijų plėtrą. Reaguodama į šiuos pokyčius, Europos Komisija 2020 m. priėmė Skaitmeninio švietimo veiksmų planą 2021--2027 m. (_Digital Education Action Plan_), kuriame suformuluota strateginė vizija dėl kokybiško, įtraukaus ir prieinamo skaitmeninio švietimo Europoje (European Commission, 2020).

Mokslinė literatūra patvirtina, kad interaktyvių technologijų integracija švietime duoda reikšmingų rezultatų, tačiau tik esant pedagoginiam tikslingumui. Freeman ir kiti (2014) atlikta didžiausia STEM disciplinų meta-analizė, apėmusi 225 tyrimus, parodė, kad aktyvaus mokymosi aplinkose, grindžiamose besimokančiojo ir turinio sąveika, egzaminų rezultatai vidutiniškai pagerėjo 0,47 standartinio nuokrypio dydžiu, o nesėkmės rodiklis tradicinių paskaitų grupėse buvo 55 proc. didesnis. Hamari, Koivisto ir Sarsa (2014), išanalizavę 24 empirinius tyrimus, nustatė, kad gamifikacija -- viena populiariausių interaktyvumo strategijų -- teikia teigiamų rezultatų, tačiau jos efektyvumas labai priklauso nuo konteksto ir vartotojų. Moore'as (1989) suformulavo tris esminius sąveikos tipus nuotoliniame ugdyme -- besimokančiojo ir turinio, besimokančiojo ir dėstytojo, besimokančiojo ir besimokančiojo sąveiką, -- kurie iki šiol sudaro interaktyvumo analizės pagrindą. Mishra ir Koehleris (2006), pasiūlę TPACK (_Technological Pedagogical Content Knowledge_) modelį, parodė, kad efektyvi technologijų integracija reikalauja technologinių, pedagoginių ir dalykinio turinio žinių sankirtos, o ne technologijos naudojimo dėl paties naujumo. Šie tyrimai rodo, kad interaktyvumo tema reikalauja ne tik technologinės, bet ir pedagoginės, socialinės bei strateginės analizės.

Lietuva šiame kontekste atsiduria savitoje pozicijoje. 2022 m. OECD PISA tyrimo duomenys rodo, kad Lietuvos penkiolikmečių matematinis raštingumas (475 taškai) nežymiai viršija OECD vidurkį (472 taškai), o šalis buvo pripažinta viena iš keturių atspariausių švietimo sistemų pasaulyje -- sugebėjusia išlaikyti arba pagerinti mokymosi rezultatus net pandemijos sąlygomis (OECD, 2023). Pagal 2024 m. TALIS tyrimo duomenis, dirbtinio intelekto priemones naudojo 39 proc. Lietuvos mokytojų -- rodiklis, viršijantis Estijos, Suomijos ir OECD vidurkį (ŠMSM, 2025). Vis dėlto skaitmeninė atskirtis tarp miesto ir kaimo mokyklų, fragmentiška strategija ir kokybiško interaktyvaus turinio lietuvių kalba trūkumas išlieka reikšmingomis problemomis, reikalaujančiomis nuodugnios analizės.

*Darbo problema.* Nors interaktyvių technologijų prieinamumas švietime per pastaruosius dešimtmečius išaugo eksponentiškai, jų pedagogiškai tikslingas ir sistemingas integravimas į ugdymo procesą tebėra neišspręsta problema. Technologijų buvimas klasėje savaime negarantuoja mokymosi kokybės -- daugelyje atvejų skaitmeniniai įrankiai naudojami kaip tradicinių priemonių pakaitalai, neišnaudojant interaktyvumo potencialo. Lietuvoje ši problema ypač aktuali: šalis pasižymi gera interneto infrastruktūra ir aukštu mokytojų DI adopcijos lygiu, tačiau stokoja ilgalaikės, nuo ES projektų ciklų nepriklausomos skaitmeninio švietimo strategijos, sisteminančios atskiras iniciatyvas į vientisą ekosistemą. Kyla klausimas: kaip interaktyvumas švietime evoliucionavo nuo ribotos skaitmeninės prieigos iki dabartinės situacijos ir kokia kryptimi turėtų judėti Lietuvos švietimo sistema, siekdama pedagogiškai prasmingos ir visiems prieinamos skaitmeninės transformacijos?

*Darbo objektas* -- interaktyvumas kaip ugdymo proceso sudedamoji dalis, apimanti technologinius įrankius, pedagogines metodikas ir besimokančiojo sąveiką su skaitmenine mokymosi aplinka.

*Darbo tikslas* -- išanalizuoti interaktyvumo raidą švietimo srityje nuo ribotos skaitmeninės prieigos iki visiško skaitmenizavimo vizijos, įvertinant Lietuvos situaciją tarptautiniame kontekste.

*Darbo uždaviniai.* Tikslui pasiekti keliami šie uždaviniai:

+ Atskleisti interaktyvumo sampratos daugiasluoksniškumą ir teorinius pagrindus, apibrėžiant sąveikos tipus ir lygius švietime.
+ Apžvelgti istorinę interaktyvumo raidą švietime -- nuo ikiskaitmeninių priemonių iki šiuolaikinės skaitmeninės transformacijos, identifikuojant esminius lūžio taškus.
+ Išnagrinėti šiuolaikines interaktyvias technologijas ugdyme -- gamifikaciją, virtualią ir papildytą realybę, dirbtinį intelektą -- ir įvertinti jų pedagoginį efektyvumą remiantis empiriniais tyrimais.
+ Atlikti lyginamąją analizę, gretinant Lietuvos skaitmeninio švietimo patirtį su Estijos, Suomijos ir Singapūro modeliais, identifikuojant sėkmės veiksnius ir perkeliamumo galimybes.
+ Suformuluoti pedagogiškai pagrįstą pilnai skaitmenizuoto ugdymo viziją, aptariant pagrindinius iššūkius ir rekomendacijas Lietuvos kontekstui.

*Darbo metodai.* Darbe taikomi šie metodai: mokslinės literatūros sisteminė analizė, apimanti edukacinių technologijų, mokymosi teorijų ir empirinių tyrimų šaltinių apžvalgą; lyginamoji analizė, skirta Lietuvos ir užsienio šalių (Estijos, Suomijos, Singapūro) švietimo skaitmenizacijos patirčių gretinimui pagal strategijos, mokytojų rengimo, platformų, DI integracijos ir mokymosi pasiekimų kriterijus; atvejo studijos, iliustruojančios konkrečių technologijų ir metodikų taikymą praktikoje.

*Darbo struktūra.* Referatas struktūriškai suskirstytas į septynias dalis. Pirmajame skyriuje analizuojama interaktyvumo samprata ir teoriniai pagrindai -- Moore'o sąveikos tipai, konstruktyvizmo, konektyvizmo ir patirtinio mokymosi teorijos. Antrajame skyriuje apžvelgiama istorinė raida nuo kreidos lentos ir radijo iki debesų kompiuterijos ir pandemijos poveikio, ypatingą dėmesį skiriant Lietuvos kontekstui. Trečiajame, plačiausiame, skyriuje nagrinėjamos šiuolaikinės interaktyvios technologijos: gamifikacija, VR/AR, dirbtinis intelektas ir kiti įrankiai, pateikiant empirinių tyrimų rezultatus ir praktinio taikymo pavyzdžius. Ketvirtajame skyriuje aptariamos pedagoginės teorijos ir metodikos -- aktyvaus mokymosi tyrimai, TPACK modelis ir formuojamasis vertinimas, -- pagrindžiančios technologijų integraciją. Penktajame skyriuje pateikiami Estijos, Suomijos, Singapūro ir Lietuvos praktiniai pavyzdžiai bei palyginamoji analizė. Šeštajame skyriuje aptariami iššūkiai: trijų lygių skaitmeninė atskirtis, mokytojų pasirengimas, turinio kokybė, ekranų laikas ir duomenų privatumas. Septintajame skyriuje formuluojama pilnai skaitmenizuoto ugdymo vizija ir konkrečios rekomendacijos Lietuvai.