
#import "../template.typ": *

= Interaktyvumo samprata ir teorinė prieiga

Siekiant analizuoti interaktyvumo raidą švietime, pirmiausia būtina apibrėžti pačią sąvoką ir jos teorinius pagrindus. Šis skyrius atskleidžia interaktyvumo daugiasluoksniškumą -- nuo etimologinės kilmės iki šiuolaikinių edukacinių-technologinių koncepcijų -- bei susieja jį su pagrindinėmis mokymosi teorijomis.

== Interaktyvumo sąvoka švietimo kontekste

Sąvoka _interaktyvumas_ kildinama iš lotyniškų žodžių _inter_ (tarp) ir _actio_ (veiksmas), tiesiogine prasme reiškiančių tarpusavio veikimą arba sąveiką. Nors terminas ilgą laiką buvo vartojamas socialinių mokslų kontekste kaip sinonimas bendravimui, pastaraisiais dešimtmečiais jis įgavo specifinę reikšmę edukacinių technologijų srityje, kur žymi aktyvią, daugiakryptę sąveiką tarp ugdymo proceso dalyvių ir skaitmeninės aplinkos.

Viena įtakingiausių interaktyvumo klasifikacijų švietime priklauso Michaelui G. Moore'ui, kuris 1989 metais suformulavo tris esminius sąveikos tipus nuotoliniame ugdyme. Pirmasis tipas -- _besimokančiojo ir turinio sąveika_ (_learner-content interaction_) -- apibūdina intelektinį procesą, kurio metu besimokantysis sąveikauja su studijuojama medžiaga, o tai lemia jo supratimo, perspektyvos ir kognityvinių struktūrų pokyčius. Moore'o teigimu, tai yra esminė švietimo charakteristika, be kurios ugdymo procesas neįmanomas (Moore, 1989). Antrasis tipas -- _besimokančiojo ir dėstytojo sąveika_ (_learner-instructor interaction_) -- aprėpia mokytojo vaidmenį motyvuojant, pateikiant turinį, organizuojant žinių taikymą bei teikiant grįžtamąjį ryšį. Trečiasis tipas -- _besimokančiojo ir besimokančiojo sąveika_ (_learner-learner interaction_) -- apima bendramokslių tarpusavio komunikaciją grupiniuose ar individualiuose kontekstuose. Moore'as akcentavo, kad būtent ši trečioji sąveikos forma taps didžiausiu iššūkiu ir galimybe artėjant XXI amžiui (Moore, 1989).

Vėliau Hillmanas, Willisas ir Gunawardena (1994) praplėtė Moore'o modelį, pridėdami ketvirtąjį sąveikos tipą -- _besimokančiojo ir sąsajos sąveiką_ (_learner-interface interaction_), kuri apibūdina besimokančiojo gebėjimą naudotis technologine priemone kaip mokymosi įrankiu. Šis papildymas ypač aktualus šiandieniniame kontekste, kai technologinė aplinka tampa neatsiejama ugdymo proceso dalimi.

Interaktyvumą taip pat galima klasifikuoti pagal besimokančiojo įsitraukimo lygį. Žemiausiame lygyje -- _pasyvaus vartojimo_ -- mokinys tik stebi ar klausosi pateikiamos informacijos, pavyzdžiui, žiūri vaizdo įrašą be galimybės jį valdyti. _Reakcinio atsako_ lygmenyje besimokantysis reaguoja į pateiktus stimulus, pavyzdžiui, atsako į testo klausimus su iš anksto parengtais atsakymų variantais. _Aktyvaus dalyvavimo_ lygmenyje mokinys tikslingai manipuliuoja mokymosi aplinka -- keičia simuliacijos parametrus, kuria turinį ar sprendžia atviras užduotis. Aukščiausiame -- _kūrybinės sąveikos_ -- lygmenyje besimokantysis pats kuria naujas žinias, bendradarbiauja su kitais ir formuoja mokymosi aplinką, pavyzdžiui, programuoja interaktyvų projektą ar kuria bendradarbiavimo pagrindu grįstą tyrimą.

Svarbu skirti interaktyvumą nuo daugiaterpės mokymosi aplinkos (_multimedia_). Multimedija apibūdina įvairių informacijos pateikimo formatų -- teksto, garso, vaizdo, grafikos -- derinimą, tačiau pats savaime daugiaterpės turinio buvimas negarantuoja interaktyvumo. Vaizdo paskaita, net ir kokybiškai pagaminta, lieka pasyviu formatu, jei nesukuria dvikryptės sąveikos galimybės. Interaktyvumas reikalauja besimokančiojo veiksmų, kurie keičia turinio pateikimą arba mokymosi proceso eigą, -- tai esminis skirtumas, lemiantis pedagoginę šių sąvokų vertę.

== Teorinė bazė

Interaktyvumo švietime svarbą pagrindžia kelios fundamentalios mokymosi teorijos, kurios, nors ir suformuluotos skirtingais laikotarpiais, tiesiogiai siejasi su aktyvios sąveikos principu.

*Konstruktyvizmas*, kurio pamatus padėjo Jeano Piaget ir Levo Vygotsky'o darbai, mokymąsi traktuoja kaip aktyvų žinių konstravimo procesą, o ne pasyvų informacijos priėmimą. Piaget (1954) pabrėžė, kad vaikai konstruoja supratimą per sąveiką su aplinka, asimiliuodami naują informaciją į esamas kognityvines schemas arba jas modifikuodami (akommodacija). Vygotsky'o (1978) socialinio konstruktyvizmo teorija papildė šį požiūrį _artimiausios raidos zonos_ (_Zone of Proximal Development_, ZPD) koncepcija, teigiančia, kad mokymasis efektyviausiai vyksta socialinėje sąveikoje su labiau patyrusiu partneriu -- mokytoju ar pažengusiu bendramoksliu. Interaktyvios technologijos, tokios kaip bendradarbiavimo platformos ar adaptyvios mokymosi sistemos, gali atlikti tokio partnerio vaidmenį, teikdamos individualizuotą pagalbą ir palaikydamos besimokantįjį jo artimiausios raidos zonoje.

*Konektyvizmas*, kurį George'as Siemensas suformulavo 2005 metais, pretenduoja būti pirmąja mokymosi teorija, specialiai sukurta skaitmeniniam amžiui. Siemensas argumentavo, kad tradicinės mokymosi teorijos -- biheviorizmas, kognityvizmas ir konstruktyvizmas -- buvo sukurtos epochoje, kai technologijos dar nebuvo fundamentaliai pakeitusios mokymosi proceso (Siemens, 2005). Konektyvizmo požiūriu, mokymasis yra specializuotų mazgų (_nodes_) arba informacijos šaltinių jungimo procesas, o žinios gali būti laikomos ne tik žmogaus atmintyje, bet ir organizacijose, duomenų bazėse ar technologiniuose tinkluose. Tarp esminių konektyvizmo principų -- gebėjimas matyti ryšius tarp skirtingų sričių, nuolatinis ryšių palaikymas kaip mokymosi sąlyga ir supratimas, kad šiandienos žinios rytoj gali tapti nebeaktualios. Nors konektyvizmo statusas kaip savarankiškos mokymosi teorijos tebėra diskutuojamas akademinėje bendruomenėje, jo principai yra itin aktualūs analizuojant interaktyvumą šiuolaikinėje skaitmeninėje mokymosi aplinkoje.

*Patirtinio mokymosi teorija*, kurią Davidas A. Kolbas pristatė 1984 metais, aprašo mokymąsi kaip ciklinį procesą, susidedantį iš keturių stadijų: konkrečios patirties, reflektyvaus stebėjimo, abstrakčios konceptualizacijos ir aktyvaus eksperimentavimo (Kolb, 1984). Interaktyvios technologijos gali palaikyti kiekvieną šio ciklo stadiją: simuliacijos ir virtualios laboratorijos suteikia konkrečią patirtį; analitiniai įrankiai ir mokymosi analitika padeda reflektyviam stebėjimui; adaptyvios platformos palengvina abstrakčią konceptualizaciją; o kūrybinės aplinkos bei programavimo įrankiai skatina aktyvų eksperimentavimą.

Galiausiai, Edgaro Dale'o *patirties kūgis* (_Cone of Experience_), pirmą kartą pristatytas 1946 metais ir atnaujintas 1969 m. knygoje _Audiovisual Methods in Teaching_, vizualizuoja mokymosi patirčių spektrą nuo labiausiai abstrakčių (verbaliniai simboliai, t. y. skaitymas) iki konkrečiausių (tiesioginė tikslinė patirtis, t. y. praktinė veikla). Nors Dale'o modelis dažnai klaidingai interpretuojamas kaip mokymosi efektyvumo hierarchija su konkrečiais įsiminimo procentais, pats autorius pabrėžė, kad kūgis yra vizualinė analogija, skirta parodyti patirčių abstraktumo progresą, o ne nustatyti, jog viena mokymosi forma yra objektyviai pranašesnė už kitą (Dale, 1969). Vis dėlto Dale'o modelis išlieka naudingas konceptualus įrankis, parodantis, kad mokymosi aplinkos, jungiančios kelis jutiminius kanalus ir skatinančios aktyvų besimokančiojo dalyvavimą -- tai yra interaktyvios aplinkos -- kuria turtingesnę (_rich_) mokymosi patirtį.

Apibendrinant, teorinė bazė rodo, kad interaktyvumas nėra vien technologinė savybė, bet fundamentalus pedagoginis principas, siejamas su aktyviu žinių konstravimu, tinkliniu mokymusi, patirtiniu ciklu ir daugiajutimiu suvokimu. Šios teorijos sudaro pagrindą tolimesnei analizei, kaip konkrečios technologijos ir pedagoginės metodikos realizuoja interaktyvumo potencialą ugdymo praktikoje.