#import "../template.typ": cite-inline

= Iššūkiai ir skaitmeninė atskirtis

Ankstesniuose skyriuose aptartos technologijos ir tarptautiniai pavyzdžiai atskleidžia interaktyvaus skaitmeninio ugdymo potencialą, tačiau šis potencialas realizuojamas toli gražu ne visada ir ne visiems vienodai. Šiame skyriuje nagrinėjami pagrindiniai iššūkiai, stabdantys interaktyvumo plėtrą švietime, pradedant nuo fundamentaliausio -- skaitmeninės atskirties.

== Skaitmeninė atskirtis

Skaitmeninė atskirtis nėra vienmatis reiškinys. Mokslinėje literatūroje ir OECD dokumentuose skiriami trys jos lygiai. *Pirminė atskirtis* -- tai nelygiavertė prieiga prie fizinės infrastruktūros: įrangos ir interneto ryšio. Vidutiniškai OECD šalyse beveik 9 iš 10 mokinių turi ir internetą, ir kompiuterį namuose, tačiau šis rodiklis maskuoja reikšmingus skirtumus tarp socioekonomiškai palankios ir nepalankios aplinkos mokinių, tarp miesto ir kaimo gyventojų. Lietuvoje ši problema sprendžiama: 2025 m. projektas „Itin spartaus ryšio infrastruktūra" pasiekė esminį lūžį -- gigabitinės spartos internetas užtikrintas 2 580 subjektams regionuose, tarp jų mokykloms ir bibliotekoms. Vis dėlto pirminė atskirtis Lietuvoje nėra visiškai įveikta, ypač atokiausiose kaimo vietovėse.

*Antrinė atskirtis* -- tai skaitmeninių kompetencijų skirtumai. Net turint prieigą prie įrangos ir interneto, ne visi mokiniai (ir ne visi mokytojai) sugeba efektyviai naudotis technologijomis mokymosi tikslais. Europoje 7 iš 10 jaunuolių (16--24 m.) turi bazinius skaitmeninius įgūdžius, tačiau tarp vyresnio amžiaus žmonių (55--64 m.) -- tik 4 iš 10. Lietuvoje 2023 m. internetu naudojosi 89 proc. gyventojų (16--74 m.), bet vyresnėje amžiaus grupėje (65--74 m.) -- tik 65 proc. Švietimo kontekste antrinė atskirtis pasireiškia tuo, kad socialiai nepalankios aplinkos mokiniai dažniau naudoja technologijas pramogoms, o ne mokymuisi, ir pasiekia žemesnius skaitmeninio raštingumo rezultatus.

*Tretinė atskirtis* -- tai gebėjimo gauti realią naudą iš technologijų nelygybė. Net turėdami prieigą ir kompetencijas, skirtingų socialinių grupių mokiniai nevienodai pasinaudoja skaitmeninėmis galimybėmis -- informacijos paieška apie karjerą, aukštąjį mokslą ar profesinį tobulėjimą. Ši atskirtis yra sunkiausiai matoma ir sunkiausiai sprendžiama, nes ji atspindi gilesnes socialines nelygybes, kurias technologijos gali ne mažinti, bet didinti.

COVID-19 pandemija skaudžiai atskleidė visų trijų lygių atskirties mastą. Priverstinis perėjimas prie nuotolinio mokymosi 2020 m. parodė, kad dalis Lietuvos mokinių neturėjo nei tinkamų įrenginių, nei stabilaus interneto ryšio, nei tinkamos darbo vietos namuose, o jų tėvai negalėjo suteikti pagalbos. ES Skaitmeninio švietimo veiksmų planas 2021--2027 buvo tiesioginis atsakas į šias pandemijos metu išryškėjusias spragas, siekiantis užtikrinti, kad skaitmeninė transformacija būtų įtrauki ir nepaliktų nė vieno nuošalyje.

== Kiti iššūkiai

*Mokytojų pasirengimas ir pasipriešinimas.* OECD _Digital Education Outlook 2023_ duomenimis, maždaug 20 proc. pagrindinės mokyklos mokytojų OECD šalyse nurodo poreikį tobulintis IKT srityje, nors 60 proc. jau buvo dalyvavę skaitmeninio ugdymo mokymuose per pastaruosius metus. Ši spraga tarp formalių mokymų ir realaus pasirengimo rodo, kad problema yra ne tiek mokymų trūkumas, kiek jų kokybė ir atitikimas praktiniams poreikiams. Lietuvoje ši situacija papildomai komplikuojama kartų skirtumo: daliai vyresniosios kartos mokytojų technologijos kelia ne tik techninius, bet ir psichologinius sunkumus -- baimę suklysti prieš mokinius, kurie technologijas valdo geriau už juos. TPACK modelis (aptartas 4 skyriuje) siūlo sisteminį sprendimą, tačiau jo įgyvendinimas reikalauja nuolatinio, ne epizodinio kvalifikacijos kėlimo.

*Turinio kokybė ir „pramoginio ugdymo" kritika.* Ne visa, kas skaitmeniniame formate ir kas vadinasi „interaktyvu", turi pedagoginę vertę. Terminas _edutainment_ (angl. _education_ + _entertainment_) apibūdina turinį, kuris prioritetizuoja pramogą mokymosi sąskaita -- spalvingus, garsius, bet paviršutiniškus skaitmeninus išteklius, kurie sukuria mokymosi iliuziją be realaus žinių konstrukto. Ši problema itin aktuali gamifikacijos kontekste: kaip aptarta 3 skyriuje, žaidimo elementai gali stipriai padidinti motyvaciją, tačiau tik tada, kai jie tarnauja pedagoginiam tikslui, o ne pakeičia jį.

*Ekranų laikas ir mokinių sveikata.* UNESCO 2023 m. pasaulinė švietimo stebėsenos ataskaita (_Global Education Monitoring Report: Technology in Education -- A Tool on Whose Terms?_) pateikė kritinį vertinimą: mokslinių įrodymų apie skaitmeninių technologijų pridėtinę vertę švietime yra mažai, o pernelyg didelis ekranų laikas neigiamai veikia vaikų psichinę sveikatą ir emocinį stabilumą. PISA 2022 duomenys tai patvirtina konkrečiais skaičiais: trys ketvirtadaliai OECD šalių mokinių praleidžia daugiau nei valandą per darbo dieną socialiniuose tinkluose, o beveik kas trečias mokinys pripažįsta, kad skaitmeniniai įrenginiai blaško dėmesį matematikos pamokose. Mokiniai, kurių dėmesį blaško kitų naudojami įrenginiai, pasiekia reikšmingai žemesnius rezultatus -- skirtumas atitinka maždaug tris ketvirčius mokslo metų. Tačiau svarbu atkreipti dėmesį į niuansą: PISA duomenys taip pat rodo, kad saikingas skaitmeninių įrenginių naudojimas mokymosi tikslais yra susijęs su geresniais rezultatais ir didesniu priklausymo mokyklai jausmu. Problema, vadinasi, nėra pačiose technologijose, o jų naudojimo būde ir intensyvume.

*Duomenų privatumas ir etika.* Interaktyvios mokymosi platformos renka didelius kiekius mokinių duomenų: mokymosi tempą, klaidų pobūdį, aktyvumo laiką, sąveikos modelius. Mokymosi analitika (aptarta 4 skyriuje) teikia vertingų įžvalgų mokytojams, tačiau kelia fundamentalius klausimus apie privatumą: kiek detaliai turėtų būti stebimas mokinio mokymosi procesas? Kas turi prieigą prie šių duomenų? Kaip užtikrinti, kad analitika netaptų mokinių klasifikavimo ir stigmatizavimo įrankiu? Europos Sąjungoje Bendrasis duomenų apsaugos reglamentas (BDAR) nustato griežtas taisykles, tačiau praktikoje daugelis švietimo institucijų naudoja komercinių bendrovių platformas (Google, Microsoft), kurių duomenų tvarkymo mechanizmai nėra pilnai skaidrūs. Vaikų duomenų apsauga reikalauja ypatingos priežiūros -- tai ne tik teisinis, bet ir etinis klausimas.

*Finansavimas ir tęstinumas.* Technologijos švietime reikalauja nuolatinių investicijų: ne tik pradiniam įsigijimui, bet ir atnaujinimui (technologijų gyvavimo ciklas -- vidutiniškai 3--5 metai), programinės įrangos licencijoms, turinio kūrimui ir mokytojų mokymui. Lietuvoje ši problema ypač opi, nes nemažai iniciatyvų finansuojamos ES struktūrinių fondų projektų ciklais -- pasibaigus projektui, neretai nutrūksta ir finansavimas, ir palaikymas. Kaip parodė 5 skyriaus palyginamoji analizė, sėkmingus modelius (Estiją, Singapūrą) nuo fragmentiškų skiria būtent ilgalaikis, nuo projektinių ciklų nepriklausomas finansavimas, integruotas į nuolatinį švietimo biudžetą.

Visi aptarti iššūkiai nėra neįveikiami, tačiau jie primena, kad interaktyvumo plėtra švietime nėra tik technologinis, bet kompleksinis -- pedagoginis, socialinis, ekonominis ir etinis -- procesas. Šį sudėtingumą būtina turėti omenyje formuluojant pilnai skaitmenizuoto ugdymo viziją, kuri aptariama paskutiniame skyriuje.
