#import "../template.typ": cite-inline

= Pilnai skaitmenizuoto ugdymo vizija

Apžvelgus interaktyvumo raidą, šiuolaikines technologijas, pedagogines metodikas, tarptautinius pavyzdžius ir iššūkius, galima bandyti formuluoti viziją: kaip galėtų atrodyti ugdymas artimiausioje ateityje ir kokį vaidmenį jame atliktų interaktyvios technologijos? Šis skyrius nagrinėja ateities tendencijas ir jų implikacijas Lietuvai, pabrėžiant, kad vizija turi būti grindžiama ne technologiniu determinizmu, o pedagoginiu tikslingumu.

== Ateities tendencijos

*AI tutoriai ir Bloomo „2 Sigma" problemos sprendimas.* 1984 m. švietimo psichologas Benjaminas Bloomas paskelbė reikšmingą atradimą: mokiniai, mokomi individualiai (1:1 tutoriaus principu) kartu taikant meistriškumo mokymąsi (_mastery learning_), pasiekdavo dviem standartiniais nuokrypiais (2σ) geresnius rezultatus nei tradiciškai mokomi bendraamžiai. Tai reiškia, kad vidutinis individualiai mokomas mokinys pranoko 98 proc. tradicinės klasės mokinių. Tačiau Bloomas pats pripažino, kad individualus tutoriavimas yra per brangus, kad būtų prieinamas masiniu mastu -- tai ir buvo vadinama „2 Sigma problema": kaip pasiekti individualaus mokymosi efektyvumą grupinio mokymosi sąlygomis?

Keturis dešimtmečius ši problema liko neišspręsta. Generatyvinio dirbtinio intelekto proveržis nuo 2022 m. atvėrė principiškai naują galimybę: AI tutoriai gali teikti personalizuotą grįžtamąjį ryšį, prisitaikyti prie kiekvieno mokinio tempo ir lygio, būti prieinami visą parą ir kainuoti daugybę kartų mažiau nei žmogaus tutorius. Tokie sprendimai kaip _Khan Academy_ su _Khanmigo_ AI asistentu, Singapūro _Adaptive Learning System_ ar Estijos _AI Leap_ programoje integruojami įrankiai jau bando šią viziją realizuoti. Tačiau svarbu neperlenkti lazdos: AI tutorius gali efektyviai tarpininkauti perteikiant turinį ir teikiant grįžtamąjį ryšį, bet negali pakeisti autentiško žmogiško santykio tarp mokytojo ir mokinio -- santykio, kuris apima empatiją, motyvavimą sudėtingose situacijose ir asmenybės ugdymą. Ateities ugdymas greičiausiai bus ne „AI vietoje mokytojo", bet „mokytojas, sustiprintas AI galimybėmis" -- kur AI perima rutininius darbus (vertinimą, turinio pritaikymą, administravimą), o mokytojas susitelkia į tai, kas žmogui sekasi geriausiai: santykių kūrimą, kritiinio mąstymo skatinimą ir vertybinį ugdymą.

*Imersinis mokymasis ir metaverse koncepcija.* Virtualios ir papildytos realybės technologijos (aptartos 3 skyriuje) evoliucionuoja link imersinio mokymosi aplinkų, kuriose mokiniai ne tik stebi, bet ir „gyvena" mokymosi patirtis. Metaverse koncepcija švietime -- virtualių mokymosi pasaulių, kuriuose mokiniai iš skirtingų geografinių vietovių gali bendradarbiauti, eksperimentuoti ir kurti -- kelia daug entuziastiškų lūkesčių. Virtualios laboratorijos, istorinių epochų rekonstrukcijos, erdvinės geometrijos ar molekulinės biologijos modeliavimas 3D erdvėje -- visa tai jau šiandien yra techniškai įmanoma. Tačiau pragmatiškas vertinimas verčia pripažinti, kad masinis VR/AR diegimas mokyklose vis dar ribotas dėl įrangos kainos, turinio kūrimo sudėtingumo ir fizinio diskomforto (_cybersickness_) problemų. Tikėtina, kad artimiausiu laikotarpiu imersinis mokymasis bus nišinė, bet vertinga priemonė specifiniams dalykams -- gamtos mokslams, medicinai, inžinerijai -- kur erdvinis suvokimas ir eksperimentavimas yra ypač svarbūs.

*Mokymosi visą gyvenimą ekosistema ir mikrokredencialai.* Ketvirtoji pramonės revoliucija ir sparti technologijų kaita reiškia, kad formalus švietimas nebegali būti baigtinis procesas, apsiribojantis mokykla ir universitetu. Mokymosi visą gyvenimą (_lifelong learning_) koncepcija tampa ne tik pedagogine idėja, bet ekonomine būtinybe. Interaktyvios technologijos šiame kontekste atveria galimybes mikrokredencialų sistemoms -- trumpiems, moduliniams, skaitmeniniu būdu sertifikuojamiems mokymosi vienetams, kurie gali būti kaupiami ir pripažįstami darbdavių. Blockchain technologija potencialiai gali užtikrinti tokių kredencialų patikimumą ir neklastojamumą. Nors ši sistema dar tik formuojasi, ji gali fundamentaliai pakeisti santykį tarp formalaus švietimo ir darbo rinkos.

== Vizija Lietuvai

Valstybės pažangos strategija „Lietuva 2050", patvirtinta Seimo, su švietimu sieja esminius lūkesčius: ateičiai pasirengusio, empatiško ir kūrybingo asmens ugdymą, intelektualinį šalies savarankiškumą ir gebėjimą kritiškai mąstyti globalių iššūkių akivaizdoje. Tačiau, kaip pažymi Seimo Ateities komiteto diskusijos dalyviai, iki šiol trūksta ilgalaikės švietimo pažangos vizijos, kuri konkrečiai susietų šiuos lūkesčius su šiandien priimamais politiniais sprendimais.

Remiantis šiame referate atlikta analize, galima formuluoti tris konkrečius veiksmus, kurie leistų Lietuvai pereiti nuo fragmentiškos skaitmenizacijos prie sisteminės interaktyvaus ugdymo plėtros.

*Pirma -- nacionalinė skaitmeninio ugdymo strategija, nepriklausoma nuo ES projektų ciklų.* Estijos ir Singapūro patirtys rodo, kad sėkminga skaitmeninė transformacija švietime reikalauja ilgalaikio, nuoseklaus planavimo, integruoto į nuolatinį švietimo biudžetą. Lietuva turėtų sukurti analogišką _Tiger Leap_ ar _EdTech Masterplan_ tipo strategiją, apibrėžiančią 10--15 metų perspektyvą su aiškiais etapais, rodikliais ir atsakomybės struktūra. ES finansavimas turėtų būti papildomas, o ne pagrindinis tokios strategijos išteklius.

*Antra -- mokytojų skaitmeninės kompetencijos kėlimas kaip sisteminė, o ne epizodinė investicija.* TPACK modelio logika (4 skyrius) ir Suomijos patirtis rodo, kad technologijų integracija priklauso ne nuo įrangos kiekio, o nuo mokytojo gebėjimo ją prasmingai naudoti. Lietuvai reikia nuolatinės, ne projektinės kvalifikacijos kėlimo sistemos, grindžiamos _DigCompEdu_ standartais, apimančios ne tik techninius, bet ir pedagoginio dizaino kompetencijas -- kaip kurti interaktyvias veiklas, kaip naudoti mokymosi analitiką, kaip integruoti AI įrankius etiškai ir efektyviai.

*Trečia -- skaitmeninio turinio lietuvių kalba ekosistemos kūrimas.* Viena didžiausių mažų kalbinių bendruomenių problemų -- turinio trūkumas gimtąja kalba. Dabartinės platformos (EMA, EDUKA) yra geras pradžios taškas, tačiau joms trūksta adaptyvumo ir kūrybinės sąveikos galimybių. Generatyvinis AI atveria naują galimybę: turinio kūrimo kaštai dramatiškai mažėja, o personalizavimo galimybės auga. Valstybė galėtų investuoti į atvirą skaitmeninio ugdymo turinio platformą, kurioje mokytojai būtų ne tik naudotojai, bet ir kūrėjai, o AI padėtų adaptuoti turinį skirtingiems mokymosi lygiams ir poreikiams.

Visus šiuos veiksmus turi vienyti vienas principas: *technologijos yra įrankis, o ne tikslas*. Kaip parodė šis referatas, pati galingiausia technologija neduoda rezultatų, jei nėra pedagoginio tikslo, mokytojo kompetencijos ir sisteminės strategijos. Pilnai skaitmenizuotas ugdymas nereiškia ugdymo be žmogaus -- priešingai, jis reiškia ugdymą, kuriame technologijos išlaisvina žmogų nuo rutinos ir suteikia erdvės tam, kas svarbiausia: mąstymui, kūrybai ir santykiams.